"""Surgical mask generator with feathering.

Creates procedure-specific inpainting masks from MediaPipe landmarks.
Masks define the region to be regenerated by the diffusion model.

Supported procedures:
  - rhinoplasty: nose dorsum + tip + wings
  - blepharoplasty: upper/lower eyelids
  - orthognathic: jaw contour + chin

Each mask is:
  1. Convex hull of procedure-specific landmarks
  2. Dilated by a configurable margin (default 20px)
  3. Gaussian-feathered for smooth blending (default sigma=12)
  4. Padded to dimensions divisible by 16 (diffusion model requirement)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

from .landmarks import (
    FaceLandmarks,
    get_region_points,
    measure_eyelid_hooding,
    measure_jaw,
    LEFT_UPPER_LID_FOLD,
    RIGHT_UPPER_LID_FOLD,
    JAW_CONTOUR,
)

log = logging.getLogger(__name__)


@dataclass
class MaskConfig:
    """Configuration for mask generation."""

    dilation_px: int = 20
    feather_sigma: float = 12.0
    pad_to_multiple: int = 16
    min_mask_area: int = 100  # minimum mask area in pixels


def generate_mask(
    landmarks: FaceLandmarks,
    procedure: str,
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a feathered surgical mask from landmarks.

    Args:
        landmarks: Extracted face landmarks.
        procedure: Surgical procedure name.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 mask in [0, 1] range, feathered at edges.
    """
    if config is None:
        config = MaskConfig()

    w, h = landmarks.image_size
    region_pts = get_region_points(landmarks, procedure)

    if len(region_pts) < 3:
        log.warning(
            "Too few landmarks (%d) for %s mask, using elliptical fallback",
            len(region_pts),
            procedure,
        )
        return _fallback_mask(w, h, procedure, config)

    # Binary mask from convex hull
    mask = np.zeros((h, w), dtype=np.uint8)
    hull = cv2.convexHull(region_pts.astype(np.int32))
    cv2.fillConvexPoly(mask, hull, 255)

    # Check minimum area
    if cv2.countNonZero(mask) < config.min_mask_area:
        log.warning("Mask area too small for %s, using elliptical fallback", procedure)
        return _fallback_mask(w, h, procedure, config)

    # Dilate to include surrounding tissue
    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    # Gaussian feathering for smooth blending
    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(
            mask, (0, 0), sigmaX=config.feather_sigma
        )

    # Normalize to [0, 1]
    mask_f = mask.astype(np.float32) / 255.0

    # Pad to multiple of pad_to_multiple
    mask_f = _pad_to_multiple(mask_f, config.pad_to_multiple)

    log.info(
        "Generated %s mask: %dx%d, coverage=%.1f%%",
        procedure,
        mask_f.shape[1],
        mask_f.shape[0],
        100.0 * (mask_f > 0.5).sum() / mask_f.size,
    )
    return mask_f


def generate_combined_mask(
    landmarks: FaceLandmarks,
    procedures: list[str],
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a combined mask for multiple procedures.

    Useful for combined surgeries (e.g., rhinoplasty + genioplasty).

    Args:
        landmarks: Extracted face landmarks.
        procedures: List of procedure names.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 combined mask in [0, 1].
    """
    if not procedures:
        raise ValueError("At least one procedure required")

    combined = None
    for proc in procedures:
        mask = generate_mask(landmarks, proc, config)
        if combined is None:
            combined = mask.copy()
        else:
            # Resize if needed (different procedures might produce different padding)
            if combined.shape != mask.shape:
                mask = cv2.resize(mask, (combined.shape[1], combined.shape[0]))
            combined = np.maximum(combined, mask)

    return combined


def generate_adaptive_bleph_mask(
    landmarks: FaceLandmarks,
    config: MaskConfig | None = None,
    intensity_pct: float = 50.0,
) -> np.ndarray:
    """Generate adaptive blepharoplasty mask with per-eye dilation.

    The more hooded eye gets more dilation so both eyes end up with
    approximately equal mask coverage.

    Args:
        landmarks: Face landmarks.
        config: Base mask config.
        intensity_pct: 0-100 intensity slider value.

    Returns:
        (H, W) float32 mask in [0, 1].
    """
    if config is None:
        config = MaskConfig()

    w, h = landmarks.image_size
    hooding = measure_eyelid_hooding(landmarks)

    # Base dilation proportional to crease-to-brow distance
    left_base = hooding["left_crease_to_brow"]
    right_base = hooding["right_crease_to_brow"]

    # More hooded eye (lower hooding ratio) gets more dilation
    left_hood = hooding["left_hooding"]
    right_hood = hooding["right_hooding"]
    max_hood = max(left_hood, right_hood, 0.1)

    # Scale: invert hooding so the MORE hooded eye gets larger dilation
    left_dilation = int(config.dilation_px * (max_hood / max(left_hood, 0.1)))
    right_dilation = int(config.dilation_px * (max_hood / max(right_hood, 0.1)))

    # Clamp to reasonable range
    left_dilation = max(5, min(left_dilation, config.dilation_px * 3))
    right_dilation = max(5, min(right_dilation, config.dilation_px * 3))

    mask = np.zeros((h, w), dtype=np.uint8)

    # Left eye mask
    left_pts = landmarks.points[[i for i in LEFT_UPPER_LID_FOLD if i < len(landmarks.points)]]
    if len(left_pts) >= 3:
        hull = cv2.convexHull(left_pts.astype(np.int32))
        left_mask = np.zeros((h, w), dtype=np.uint8)
        cv2.fillConvexPoly(left_mask, hull, 255)
        if left_dilation > 0:
            ksize = 2 * left_dilation + 1
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
            left_mask = cv2.dilate(left_mask, kernel, iterations=1)
        mask = np.maximum(mask, left_mask)

    # Right eye mask
    right_pts = landmarks.points[[i for i in RIGHT_UPPER_LID_FOLD if i < len(landmarks.points)]]
    if len(right_pts) >= 3:
        hull = cv2.convexHull(right_pts.astype(np.int32))
        right_mask = np.zeros((h, w), dtype=np.uint8)
        cv2.fillConvexPoly(right_mask, hull, 255)
        if right_dilation > 0:
            ksize = 2 * right_dilation + 1
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
            right_mask = cv2.dilate(right_mask, kernel, iterations=1)
        mask = np.maximum(mask, right_mask)

    # Feather
    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0

    # Inpainting strength scaling
    strength = 0.3 + 0.25 * (intensity_pct / 100.0)

    log.info(
        "Adaptive bleph mask: L_dil=%d R_dil=%d L_hood=%.2f R_hood=%.2f strength=%.2f",
        left_dilation, right_dilation, left_hood, right_hood, strength,
    )
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def generate_adaptive_rhytid_mask(
    landmarks: FaceLandmarks,
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate adaptive rhytidectomy mask following the jaw contour.

    The mask follows the actual jaw contour (not a horizontal line),
    with a 5px feather along the contour. The neck region extends to
    the bottom of the image.

    Args:
        landmarks: Face landmarks.
        config: Base mask config.

    Returns:
        (H, W) float32 mask in [0, 1].
    """
    if config is None:
        config = MaskConfig()

    w, h = landmarks.image_size
    pts = landmarks.points
    jaw = measure_jaw(landmarks)

    mask = np.zeros((h, w), dtype=np.uint8)

    # Build jaw contour polygon that extends to image bottom
    jaw_indices = [i for i in JAW_CONTOUR if i < len(pts)]
    if len(jaw_indices) < 5:
        return _fallback_mask(w, h, "rhytidectomy", config)

    jaw_pts = pts[jaw_indices].astype(np.int32)

    # Sort jaw points left-to-right for a clean contour
    sorted_jaw = jaw_pts[jaw_pts[:, 0].argsort()]

    # Create polygon: jaw contour + image bottom corners
    contour = list(sorted_jaw)
    # Extend to image edges at bottom
    contour.append([w - 1, h - 1])
    contour.append([0, h - 1])
    contour = np.array(contour, dtype=np.int32)

    # Fill below-jaw region (neck + jawline)
    cv2.fillPoly(mask, [contour], 255)

    # Check if image includes significant neck area
    chin_y = jaw["chin_y"]
    neck_extent = h - chin_y
    has_neck = neck_extent > h * 0.1  # at least 10% of image below chin

    if not has_neck:
        # Image cropped at chin -- only do jawline, skip neck
        # Restrict mask to a band around the jaw contour
        jaw_band = np.zeros((h, w), dtype=np.uint8)
        for i in range(len(sorted_jaw) - 1):
            cv2.line(jaw_band, tuple(sorted_jaw[i]), tuple(sorted_jaw[i + 1]), 255, 20)
        mask = cv2.bitwise_and(mask, jaw_band)
        log.info("Rhytid mask: chin-cropped image, jawline only")

    # Feather along jaw contour (5px)
    feather_mask = np.zeros((h, w), dtype=np.uint8)
    for i in range(len(sorted_jaw) - 1):
        cv2.line(feather_mask, tuple(sorted_jaw[i]), tuple(sorted_jaw[i + 1]), 255, 10)
    feather_mask = cv2.GaussianBlur(feather_mask, (0, 0), sigmaX=5)

    # Combine: hard mask below jaw, feathered at contour
    mask_f = mask.astype(np.float32) / 255.0
    feather_f = feather_mask.astype(np.float32) / 255.0

    # The upper boundary of the mask gets the feather treatment
    mask_f = np.maximum(mask_f, feather_f * 0.5)

    if config.feather_sigma > 0:
        mask_f = cv2.GaussianBlur(mask_f, (0, 0), sigmaX=config.feather_sigma / 2)

    log.info(
        "Adaptive rhytid mask: jaw_w=%.0f chin_y=%.0f has_neck=%s",
        jaw["jaw_width"], chin_y, has_neck,
    )
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def mask_to_pil(mask: np.ndarray) -> Image.Image:
    """Convert float32 mask [0,1] to PIL Image (L mode, [0,255])."""
    return Image.fromarray((mask * 255).astype(np.uint8), mode="L")


def save_mask(mask: np.ndarray, path: str | Path) -> None:
    """Save mask as PNG."""
    mask_to_pil(mask).save(str(path))
    log.info("Saved mask to %s", path)


def _fallback_mask(
    w: int,
    h: int,
    procedure: str,
    config: MaskConfig,
) -> np.ndarray:
    """Generate a heuristic elliptical mask when landmarks are insufficient."""
    mask = np.zeros((h, w), dtype=np.uint8)

    # Approximate mask centers relative to image dimensions
    params = {
        "rhinoplasty": (0.50, 0.55, 0.12, 0.15),
        "blepharoplasty": (0.50, 0.38, 0.25, 0.06),
        "orthognathic": (0.50, 0.72, 0.20, 0.18),
        "rhytidectomy": (0.50, 0.60, 0.35, 0.30),
    }
    cx_r, cy_r, rx_r, ry_r = params.get(procedure, (0.50, 0.50, 0.15, 0.15))

    cx, cy = int(w * cx_r), int(h * cy_r)
    rx, ry = int(w * rx_r), int(h * ry_r)
    cv2.ellipse(mask, (cx, cy), (rx, ry), 0, 0, 360, 255, -1)

    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def _pad_to_multiple(mask: np.ndarray, multiple: int) -> np.ndarray:
    """Pad mask so dimensions are divisible by `multiple`."""
    h, w = mask.shape[:2]
    new_h = ((h + multiple - 1) // multiple) * multiple
    new_w = ((w + multiple - 1) // multiple) * multiple
    if new_h == h and new_w == w:
        return mask
    padded = np.zeros((new_h, new_w), dtype=mask.dtype)
    padded[:h, :w] = mask
    return padded
