"""Surgical mask generator with feathering.

Creates procedure-specific inpainting masks from MediaPipe landmarks.
Masks define the region to be regenerated by the diffusion model.

Supported procedures:
  - rhinoplasty: nose dorsum + tip + wings
  - blepharoplasty: upper/lower eyelids
  - 

Each mask is:
  1. Convex hull of procedure-specific landmarks
  2. Dilated by a configurable margin (default 20px)
  3. Gaussian-feathered for smooth blending (default sigma=12)
  4. Padded to dimensions divisible by 16 (diffusion model requirement)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

from .landmarks import FaceLandmarks, get_region_points

log = logging.getLogger(__name__)


@dataclass
class MaskConfig:
    """Configuration for mask generation."""

    dilation_px: int = 20
    feather_sigma: float = 12.0
    pad_to_multiple: int = 16
    min_mask_area: int = 100  # minimum mask area in pixels


def generate_mask(
    landmarks: FaceLandmarks,
    procedure: str,
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a feathered surgical mask from landmarks.

    Args:
        landmarks: Extracted face landmarks.
        procedure: Surgical procedure name.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 mask in [0, 1] range, feathered at edges.
    """
    if config is None:
        config = MaskConfig()

    w, h = landmarks.image_size
    region_pts = get_region_points(landmarks, procedure)

    if len(region_pts) < 3:
        log.warning(
            "Too few landmarks (%d) for %s mask, using elliptical fallback",
            len(region_pts),
            procedure,
        )
        return _fallback_mask(w, h, procedure, config)

    # Binary mask from convex hull
    mask = np.zeros((h, w), dtype=np.uint8)
    hull = cv2.convexHull(region_pts.astype(np.int32))
    cv2.fillConvexPoly(mask, hull, 255)

    # Check minimum area
    if cv2.countNonZero(mask) < config.min_mask_area:
        log.warning("Mask area too small for %s, using elliptical fallback", procedure)
        return _fallback_mask(w, h, procedure, config)

    # Dilate to include surrounding tissue
    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    # Gaussian feathering for smooth blending
    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(
            mask, (0, 0), sigmaX=config.feather_sigma
        )

    # Normalize to [0, 1]
    mask_f = mask.astype(np.float32) / 255.0

    # Pad to multiple of pad_to_multiple
    mask_f = _pad_to_multiple(mask_f, config.pad_to_multiple)

    log.info(
        "Generated %s mask: %dx%d, coverage=%.1f%%",
        procedure,
        mask_f.shape[1],
        mask_f.shape[0],
        100.0 * (mask_f > 0.5).sum() / mask_f.size,
    )
    return mask_f


def generate_combined_mask(
    landmarks: FaceLandmarks,
    procedures: list[str],
    config: MaskConfig | None = None,
) -> np.ndarray:
    """Generate a combined mask for multiple procedures.

    Useful for combined surgeries (e.g., rhinoplasty + genioplasty).

    Args:
        landmarks: Extracted face landmarks.
        procedures: List of procedure names.
        config: Mask generation parameters.

    Returns:
        (H, W) float32 combined mask in [0, 1].
    """
    if not procedures:
        raise ValueError("At least one procedure required")

    combined = None
    for proc in procedures:
        mask = generate_mask(landmarks, proc, config)
        if combined is None:
            combined = mask.copy()
        else:
            # Resize if needed (different procedures might produce different padding)
            if combined.shape != mask.shape:
                mask = cv2.resize(mask, (combined.shape[1], combined.shape[0]))
            combined = np.maximum(combined, mask)

    return combined


def mask_to_pil(mask: np.ndarray) -> Image.Image:
    """Convert float32 mask [0,1] to PIL Image (L mode, [0,255])."""
    return Image.fromarray((mask * 255).astype(np.uint8), mode="L")


def save_mask(mask: np.ndarray, path: str | Path) -> None:
    """Save mask as PNG."""
    mask_to_pil(mask).save(str(path))
    log.info("Saved mask to %s", path)


def _fallback_mask(
    w: int,
    h: int,
    procedure: str,
    config: MaskConfig,
) -> np.ndarray:
    """Generate a heuristic elliptical mask when landmarks are insufficient."""
    mask = np.zeros((h, w), dtype=np.uint8)

    # Approximate mask centers relative to image dimensions
    params = {
        "rhinoplasty": (0.50, 0.55, 0.12, 0.15),
        "blepharoplasty": (0.50, 0.38, 0.25, 0.06),
        "rhytidectomy": (0.50, 0.60, 0.35, 0.30),
    }
    cx_r, cy_r, rx_r, ry_r = params.get(procedure, (0.50, 0.50, 0.15, 0.15))

    cx, cy = int(w * cx_r), int(h * cy_r)
    rx, ry = int(w * rx_r), int(h * ry_r)
    cv2.ellipse(mask, (cx, cy), (rx, ry), 0, 0, 360, 255, -1)

    if config.dilation_px > 0:
        ksize = 2 * config.dilation_px + 1
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
        mask = cv2.dilate(mask, kernel, iterations=1)

    if config.feather_sigma > 0:
        mask = cv2.GaussianBlur(mask, (0, 0), sigmaX=config.feather_sigma)

    mask_f = mask.astype(np.float32) / 255.0
    return _pad_to_multiple(mask_f, config.pad_to_multiple)


def _pad_to_multiple(mask: np.ndarray, multiple: int) -> np.ndarray:
    """Pad mask so dimensions are divisible by `multiple`."""
    h, w = mask.shape[:2]
    new_h = ((h + multiple - 1) // multiple) * multiple
    new_w = ((w + multiple - 1) // multiple) * multiple
    if new_h == h and new_w == w:
        return mask
    padded = np.zeros((new_h, new_w), dtype=mask.dtype)
    padded[:h, :w] = mask
    return padded
